
# 支持格式：
# title: 标题
filename_format = '%Y-%m-%d-{title}'


[Article]
# 文章属性配置
floder = './content'
# 文章中的日期格式设置
date_format = '%Y-%m-%d %H:%M:%S'
# 文件名格式, 不包含后缀, title 代表文章标题
filename_format = '%Y-%m-%d-{title}'
# 文章默认作者
author = ''
